# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Doesn't insert a blank line between shell prompts
add_newline = false

# Change the line that appears before the cursor
format = '$git_branch $git_status$line_break($nodejs |)($deno |)($rust|) $directory$character'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[rust]
format = '[$symbol($version )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[deno]
format = '[$symbol($version )]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
